apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promo-data-pvc
  namespace: ecommerce
spec:
  storageClassName: "ocs-storagecluster-cephfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi