# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: mongo
#   name: mongo-svc
#   namespace: ecommerce
# spec:
#   ports:
#   - port: 27017
#     protocol: TCP
#     targetPort: 27017
#     nodePort: 32001
#   selector:
#     app: mongo
#   type: NodePort
# status:
#   loadBalancer: {}


apiVersion: "v1"
kind: "Service"
metadata: 
  name: "mongo-db"
  namespace: "development"
  labels: 
    app: "mongo-db"
spec: 
  ports: 
    - 
      name: "mongodb"
      port: 27017
      targetPort: 27017
  clusterIP: "None"
  selector: 
    app: "mongo-db"