apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-pvc
  namespace: ecommerce
spec:
  storageClassName: "ocs-storagecluster-ceph-rbd"
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 5Gi