apiVersion: "apps/v1"
kind: "StatefulSet"
metadata: 
  name: "mongo-db"
  namespace: "development"
spec:
  serviceName: "mongo-db" 
  replicas: 1
  selector: 
    matchLabels: 
      app: "mongo-db"
  template: 
    metadata: 
      labels: 
        app: "mongo-db"
    spec: 
      containers: 
        - name: "mongo-db"
          image: "docker.io/mongo"
          imagePullPolicy: "Always"
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-creds
                key: password
          ports: 
            - containerPort: 27017
              name: "mongodb"
          volumeMounts: 
            - name: "mongodb-persistent-storage"
              mountPath: "/data/db"
              
      volumes: 
        - name: "mongodb-persistent-storage"
          persistentVolumeClaim: 
            claimName: "mongo-data-pvc"