name: image-publisher

on: 
  workflow_dispatch:
    inputs:
      REGISTRY_NAMESPACE:
        required: true
        default: rh_ee_mrudraia
      IMAGE_TAG:
        required: false
        default: latest

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
