---
name: ecommerce app sanity checks

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

  workflow_dispatch:
    inputs:
      REGISTRY_NAMESPACE:
        required: true
        default: rh_ee_mrudraia
      IMAGE_TAG:
        required: false
        default: latest


jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      # - name: Run shellcheck
      #   run: make shellcheck-test 

  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest

    steps:
    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and push to Quay
      # uses: docker/build-push-action@v5
      # with:
      #   context:
      #   push: true
      #   tags: marula
      #   run: 
      env:
        REGISTRY_NAMESPACE: ${{ github.event.inputs.REGISTRY_NAMESPACE }}
        IMAGE_TAG: ${{ github.event.inputs.IMAGE_TAG }}
        IMAGE_TAG_SHA: ${{ github.ref_name }}-${{ github.sha }}
        IMAGE_BUILD_CMD: docker
      run: |
        # set IMAGE_TAG to a calculated <branch>-<sha> if not specified
        export IMAGE_TAG=${IMAGE_TAG:-${IMAGE_TAG_SHA:0:-33}}

        make build-frontend
        make push-frontend
