---
name: ecommerce app sanity checks

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]


jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Run shellcheck
        run: make shellcheck-test 

  build-frontend:
    name: build-frontend
    runs-on: ubuntu-latest

    steps:
    - name: Login to Quay
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build and psh to Quay
      uses: docker/build-push-action@v5
      with:
        context:
        push: true
        tags: marula
