name: Openshift Deployment

on:
  workflow_dispatch:
    inputs:
      REGISTRY_NAMESPACE:
        required: true
        default: rh_ee_mrudraia
      IMAGE_TAG:
        required: false
        default: ""

jobs:
  deploy:
    stage: deploy
    image: {Link: debianmaster/gitlab-oc-cli https://github.com/debianmaster/gitlab-oc-cli}:latest
    script:
      - oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}
      - oc project ecommerce-app
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v3

    # - name: Login to Openshift
    #   run: oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}

    # - name: Deploy to Openshift
    #   run: oc apply -f ecommerce-k8s/