name: Openshift Deployment

on:
  workflow_dispatch:
    inputs:
      REGISTRY_NAMESPACE:
        required: true
        default: rh_ee_mrudraia
      IMAGE_TAG:
        required: false
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download Openshift CLI
      run: curl "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz" --output openshift-client-linux.tar.gz

    - name: Install the Openshift cli
      run: |
          tar -xvf openshift-client-linux.tar.gz  
          sudo mv oc /usr/local/bin/

    - name: Check oc version
      run: oc version

    # - name: Login to Openshift
    #   run: oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }}

    # - name: Deploy to Openshift
    #   run: oc apply -f ecommerce-k8s/
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        # certificate_authority_data: ${{ secrets.CA_DATA }}
        insecure_skip_tls_verify: true
        openshift_username: ${{ vars.OPENSHIFT_USER }}
        openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}

    - name: Deploy to openshift
      run: oc get nodes